# Generated by Django 4.0.3 on 2022-06-29 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceToVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('places_to_visit', models.CharField(max_length=300)),
                ('country_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=300)),
                ('post_title', models.CharField(max_length=300)),
                ('post_text', models.CharField(max_length=5000)),
                ('release_date', models.DateTimeField()),
                ('places_to_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.placetovisit')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='media/')),
                ('places_to_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.placetovisit')),
            ],
        ),
    ]
