# Generated by Django 4.0.3 on 2022-06-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_image2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image2',
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
